### PR TITLE
control-group fix

### PR DESCRIPTION
**Pull request by ciprianbadescu**
Don't wait for children to die if killMode is not control-group

### CODE REVIEW

**Comment by gdraheim** [comment]
the patch looks weird, did you check it with the testsuite? Why is it only for the SendSIGHUP case?

**Comment by ciprianbadescu** [comment]
In my use there was a sshd service restart (KillMode=process) that was waiting all sessions to be stopped.
Let me know if it should apply also to stop or other cases and if you prefer different approach (implement specific process killMode and keep existing default behavior)

**Comment by gdraheim** [comment]
The patch does not change the wait-loop at all, right?

So in a way we do stop the "kill" to send a SigHUP to child process, but the function will netherthless wait for all children. So for your scenario, you can keep the child process of sshd but the service-stop will always wait for the timeout to happen.

From my point of view, a better approach to the topic would be to reduce the "pidlist" to the main process if KillMode=process, correct?

**Comment by ciprianbadescu** [comment]
Yes, this will be better solution with the same result

**Comment by gdraheim** [comment]
I have double checked with https://www.freedesktop.org/software/systemd/man/systemd.kill.html
and it seems that the shorting of pidlist itself will defeat the KillMode=mixed where the initial SIGTERM is sent to the MainPID only but the later SIGKILL goes to all children. So it does basically clean up if the main-proc had done its share fully.

May be a seperation of pidlist1 and pidlist2 will help?

**Pull request closed without merging**
